{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "E   assert False"}, "description": "Test que prueba Allure de nuevo", "start": 1652975534641, "stop": 1652975534641, "uuid": "bff2201a-2f12-4826-886a-cff497b05301", "historyId": "7894dcaea4d3fb737f6762661f608dc5", "testCaseId": "eb4efc295694a4a70210f35830a78214", "fullName": "tests.test_10_allure.TestReports#test_2", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "cashin"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_10_allure"}, {"name": "subSuite", "value": "TestReports"}, {"name": "host", "value": "WKSAR1848L.local"}, {"name": "thread", "value": "5519-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_10_allure"}]}